site_name: Learn AI Fundamentals
site_url: https://codebygk.github.io/learn-ai-fundamentals/
repo_url: https://github.com/codebygk/learn-ai-fundamentals
repo_name: codebygk/learn-ai-fundamentals

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
plugins:
  - search
  - awesome-pages
