site_name: Learn AI Fundamentals
site_url: https://codebygk.github.io/learn-ai-fundamentals/
repo_url: https://github.com/codebygk/learn-ai-fundamentals
repo_name: codebygk/learn-ai-fundamentals

theme:
  name: material
  favicon: assets/images/book.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: bluegrey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: bluegrey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference  features
  features:
    - navigation.tabs
    - navigation.tabs.icons # must enable this
    - navigation.tabs.scroll
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  # turn OFF codehilite linenums
  - codehilite:
      guess_lang: false

  # use pymdownx.highlight instead
  - pymdownx.highlight:
      linenums: true # this actually shows the numbers
      anchor_linenums: true # makes them clickable
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - awesome-pages

extra_css:
  - assets/css/styles.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/codebygk/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/codebygk
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codebygk
      name: Twitter
